version: "3.9"
services:
  my-container:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GIT_USER=ahaas207
      - GIT_REPO=DemoStructuredCOS160
      - PASSWORD=Password
    ports:
      - "6080:6080"
      - "5901:5901"
    volumes:
      - .:/workspace
    stdin_open: true
    tty: true
